# Generated by Django 2.1.1 on 2018-10-10 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EloLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True)),
                ('elo', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True)),
                ('ranked', models.BooleanField(default=True)),
                ('winner', models.CharField(choices=[('team1', 'Équipe 1'), ('team2', 'Équipe 2')], default='team1', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GameMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GameReplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replay', models.FileField(upload_to='games/')),
                ('minimap', models.ImageField(blank=True, default='', upload_to='minimaps/')),
                ('chronology', models.ImageField(blank=True, default='', upload_to='researches/')),
                ('game_version', models.CharField(blank=True, default='', max_length=20)),
                ('game_type', models.CharField(blank=True, default='Standard Game', max_length=50)),
                ('population_limit', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('speed', models.CharField(blank=True, default='normal', max_length=20)),
                ('difficulty', models.CharField(blank=True, default='normal', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('firstname', models.CharField(blank=True, default=None, max_length=50)),
                ('lastname', models.CharField(blank=True, default=None, max_length=50)),
                ('ngames', models.PositiveIntegerField(default=0)),
                ('elo', models.PositiveIntegerField(default=0)),
                ('init_elo', models.PositiveIntegerField(default=1400)),
                ('avatar', models.ImageField(blank=True, default=None, upload_to='avatars/')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('team', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('civilization', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('resign_time', models.PositiveIntegerField(blank=True, default=0)),
                ('identity', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gametracker.Identity')),
            ],
        ),
        migrations.AddField(
            model_name='identity',
            name='person',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='gametracker.Person'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gametracker.GameMap'),
        ),
        migrations.AddField(
            model_name='game',
            name='replay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gametracker.GameReplay'),
        ),
        migrations.AddField(
            model_name='game',
            name='team1',
            field=models.ManyToManyField(related_name='team1', to='gametracker.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='team2',
            field=models.ManyToManyField(related_name='team2', to='gametracker.Player'),
        ),
        migrations.AddField(
            model_name='elolog',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gametracker.Person'),
        ),
    ]
