# Generated by Django 2.1.1 on 2018-10-15 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gametracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='person',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gametracker.Person'),
        ),
    ]
