# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gametracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='team2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team2', to='gametracker.Team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='team1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team1', to='gametracker.Team'),
        ),
    ]
