# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gametracker', '0002_auto_20170911_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='elo',
            field=models.PositiveIntegerField(default=1400),
        ),
        migrations.AddField(
            model_name='player',
            name='ngames',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
