# Generated by Django 2.1.1 on 2018-10-15 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gametracker', '0002_auto_20181015_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='identity',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='gametracker.Identity'),
        ),
    ]
