# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gametracker', '0003_auto_20170912_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
