# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gametracker', '0004_auto_20170912_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='firstname',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='lastname',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
