# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gametracker', '0005_auto_20170912_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='map_name',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='firstname',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='lastname',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
