# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gametracker', '0006_auto_20170913_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='winner',
        ),
    ]
