# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gametracker', '0007_remove_team_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.CharField(choices=[('team1', 'Equipe 1'), ('team2', 'Equipe 2')], default='team1', max_length=20),
        ),
    ]
