# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gametracker', '0008_game_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='map_name',
            field=models.CharField(blank=True, choices=[('Arabia', 'Arabie'), ('Continental', 'Continent'), ('Islands', '\xceles'), ('Rivers', 'Rivi\xe8res'), ('Scandinavia', 'Scandinavie')], default=None, max_length=100),
        ),
    ]
