# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gametracker', '0009_auto_20170913_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='map_name',
        ),
        migrations.AddField(
            model_name='game',
            name='game_map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gametracker.GameMap'),
        ),
    ]
