# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gametracker', '0010_auto_20170913_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='players',
        ),
        migrations.RemoveField(
            model_name='game',
            name='team1',
        ),
        migrations.AddField(
            model_name='game',
            name='team1',
            field=models.ManyToManyField(related_name='team1', to='gametracker.Player'),
        ),
        migrations.RemoveField(
            model_name='game',
            name='team2',
        ),
        migrations.AddField(
            model_name='game',
            name='team2',
            field=models.ManyToManyField(related_name='team2', to='gametracker.Player'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
