# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gametracker', '0011_auto_20170916_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gametracker.GameMap'),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(choices=[('team1', '\xc9quipe 1'), ('team2', '\xc9quipe 2')], default='team1', max_length=20),
        ),
    ]
